PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix org: <http://www.w3.org/ns/org#> 

SELECT ?managementName (COUNT(?filia) AS ?filiaCount) WHERE {
  ?filia a org:OrganizationalUnit .
  ?filia org:reportsTo ?management .
  
  ?management schema:name ?managementName .
}
GROUP BY ?managementName
ORDER BY DESC (?filiaCount)
