PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix org: <http://www.w3.org/ns/org#> 
prefix vcard: <http://www.w3.org/2006/vcard/ns#> 

SELECT ?region (COUNT(?filia) AS ?filiaCount) WHERE {
  ?filia a org:OrganizationalUnit .
  ?filia vcard:region ?region .
}
GROUP BY ?region
ORDER BY DESC (?filiaCount)