PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX schema: <http://schema.org/>

SELECT ?person ?firstName ?lastName ?workplaceName ?date
WHERE {
  ?person foaf:firstName ?firstName;
          foaf:lastName ?lastName;
  		  schema:worksFor ?workplace;
      <http://example.org/radon#startedCurrentJob> ?date.
      
  ?workplace schema:name ?workplaceName.
  VALUES (?firstName ?lastName) {
    ("Maria" "Ganzha")
    ("Jan" "Bródka")
    ("Hubert" "Pająk")
    ("Marcin" "Paprzycki")
    ("Paweł" "Szmeja")
    ("Wojciech" "Matysiak")
    ("Barbara" "Roszkowska-Lech")
  }
}
